# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 15s

# Alert manager configuration
rule_files:
- /etc/prometheus/alert_rules.yml

scrape_configs:
- job_name: 'spring'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['host.docker.internal:8080']

#Configuration of the alert manager
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "host.docker.internal:9093"